//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodwinService3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kompasEntities : DbContext
    {
        public kompasEntities()
            : base("name=kompasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<currency> currency { get; set; }
        public virtual DbSet<doctype> doctype { get; set; }
        public virtual DbSet<external_document> external_document { get; set; }
        public virtual DbSet<freight> freight { get; set; }
        public virtual DbSet<hotel> hotel { get; set; }
        public virtual DbSet<htplace> htplace { get; set; }
        public virtual DbSet<meal> meal { get; set; }
        public virtual DbSet<opeople> opeople { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<people> people { get; set; }
        public virtual DbSet<room> room { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<service> service { get; set; }
        public virtual DbSet<insure> insure { get; set; }
        public virtual DbSet<visa> visa { get; set; }
        public virtual DbSet<visapr> visapr { get; set; }
        public virtual DbSet<reserve> reserve { get; set; }
        public virtual DbSet<@class> @class { get; set; }
        public virtual DbSet<claim> claim { get; set; }
        public virtual DbSet<partner> partner { get; set; }
        public virtual DbSet<payment> payment { get; set; }
        public virtual DbSet<pdetail> pdetail { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
