//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodwinService3
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doctype()
        {
            this.external_document = new HashSet<external_document>();
        }
    
        public int inc { get; set; }
        public string name { get; set; }
        public string lname { get; set; }
        public string alias { get; set; }
        public string module { get; set; }
        public Nullable<int> doccategory { get; set; }
        public string note { get; set; }
        public string upload_format { get; set; }
        public Nullable<int> upload_size { get; set; }
        public bool upload_online { get; set; }
        public Nullable<bool> @private { get; set; }
        public bool upload_req_people { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<external_document> external_document { get; set; }
    }
}
