//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodwinService3
{
    using System;
    using System.Collections.Generic;
    
    public partial class external_document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public external_document()
        {
            this.opeople2 = new HashSet<opeople>();
        }
    
        public int inc { get; set; }
        public int claim { get; set; }
        public Nullable<int> people { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public string mime_type { get; set; }
        public byte[] content { get; set; }
        public System.DateTime cdate { get; set; }
        public System.DateTime edate { get; set; }
        public Nullable<System.DateTime> odate { get; set; }
        public string FileName { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<int> opeople { get; set; }
        public bool @private { get; set; }
        public Nullable<int> doctype { get; set; }
        public int document_status { get; set; }
        public System.DateTime adate { get; set; }
        public string status_note { get; set; }
        public Nullable<System.DateTime> status_date { get; set; }
        public Nullable<short> status_user { get; set; }
        public bool incoming { get; set; }
    
        public virtual doctype doctype1 { get; set; }
        public virtual opeople opeople1 { get; set; }
        public virtual order order1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<opeople> opeople2 { get; set; }
        public virtual claim claim1 { get; set; }
    }
}
