//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodwinService3
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hotel()
        {
            this.order = new HashSet<order>();
            this.order1 = new HashSet<order>();
        }
    
        public int inc { get; set; }
        public string name { get; set; }
        public string lname { get; set; }
        public int star { get; set; }
        public int partner { get; set; }
        public int town { get; set; }
        public string address { get; set; }
        public string phprefix { get; set; }
        public string phones { get; set; }
        public string faxes { get; set; }
        public string email { get; set; }
        public Nullable<short> stopsale { get; set; }
        public bool tennis { get; set; }
        public Nullable<System.DateTime> checkintime { get; set; }
        public Nullable<System.DateTime> checkouttime { get; set; }
        public bool pernight { get; set; }
        public string catalogpage { get; set; }
        public string www { get; set; }
        public Nullable<System.DateTime> addcheckintime { get; set; }
        public Nullable<System.DateTime> addcheckouttime { get; set; }
        public string alias { get; set; }
        public Nullable<bool> appartaments { get; set; }
        public Nullable<bool> commission { get; set; }
        public byte[] stamp { get; set; }
        public Nullable<int> minage { get; set; }
        public int printtype { get; set; }
        public bool descr_completed { get; set; }
        public Nullable<int> currency { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public bool isarchive { get; set; }
        public Nullable<short> adult_noconfirm_less { get; set; }
        public Nullable<short> adult_noconfirm_more { get; set; }
        public Nullable<short> pax_noconfirm_more { get; set; }
        public bool malestop { get; set; }
        public bool noconfirm_infant { get; set; }
        public bool freeinfant { get; set; }
        public bool childonadlseat { get; set; }
        public string checkindays { get; set; }
        public string checkoutdays { get; set; }
    
        public virtual currency currency1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> order1 { get; set; }
        public virtual partner partner1 { get; set; }
    }
}
