//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodwinService3
{
    using System;
    using System.Collections.Generic;
    
    public partial class htplace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public htplace()
        {
            this.order = new HashSet<order>();
        }
    
        public int inc { get; set; }
        public string name { get; set; }
        public string lname { get; set; }
        public Nullable<byte> adult { get; set; }
        public Nullable<byte> child { get; set; }
        public Nullable<byte> infant { get; set; }
        public short sort { get; set; }
        public Nullable<decimal> age1min { get; set; }
        public Nullable<decimal> age1max { get; set; }
        public Nullable<decimal> age2min { get; set; }
        public Nullable<decimal> age2max { get; set; }
        public Nullable<decimal> age3min { get; set; }
        public Nullable<decimal> age3max { get; set; }
        public byte[] stamp { get; set; }
        public short nobedchild { get; set; }
        public Nullable<decimal> age0min { get; set; }
        public Nullable<decimal> age0max { get; set; }
        public Nullable<byte> pcount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> order { get; set; }
    }
}
