//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodwinService3
{
    using System;
    using System.Collections.Generic;
    
    public partial class insure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public insure()
        {
            this.order = new HashSet<order>();
        }
    
        public int inc { get; set; }
        public string name { get; set; }
        public string lname { get; set; }
        public Nullable<int> partner { get; set; }
        public int state { get; set; }
        public Nullable<short> old_nights { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> net { get; set; }
        public Nullable<int> currency { get; set; }
        public string zone { get; set; }
        public Nullable<bool> commission { get; set; }
        public bool is_medical { get; set; }
        public Nullable<decimal> percent { get; set; }
        public bool auto_datebeg { get; set; }
        public Nullable<decimal> tcsum { get; set; }
        public Nullable<int> tccurrency { get; set; }
        public Nullable<decimal> netpercent { get; set; }
        public byte[] stamp { get; set; }
        public short percent_from { get; set; }
        public short netpercent_from { get; set; }
        public Nullable<bool> excludeinf { get; set; }
        public int printtype { get; set; }
        public byte tcdateend { get; set; }
        public string www { get; set; }
        public Nullable<int> color { get; set; }
        public byte mdatebeg { get; set; }
        public int inszone { get; set; }
        public Nullable<bool> excludemedins { get; set; }
        public int insuretype { get; set; }
        public Nullable<System.DateTime> datebeg { get; set; }
        public Nullable<System.DateTime> dateend { get; set; }
        public string info1 { get; set; }
        public bool complete { get; set; }
        public Nullable<int> nationality { get; set; }
        public bool limitbytcsum { get; set; }
        public string territory { get; set; }
        public bool apply_insage { get; set; }
        public Nullable<decimal> tcsumfrom { get; set; }
        public Nullable<decimal> agetill { get; set; }
        public Nullable<int> mindaysbeforetour { get; set; }
    
        public virtual currency currency1 { get; set; }
        public virtual currency currency2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> order { get; set; }
        public virtual partner partner1 { get; set; }
    }
}
