//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodwinService3
{
    using System;
    using System.Collections.Generic;
    
    public partial class partner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public partner()
        {
            this.claim = new HashSet<claim>();
            this.claim1 = new HashSet<claim>();
            this.claim2 = new HashSet<claim>();
            this.claim3 = new HashSet<claim>();
            this.freight = new HashSet<freight>();
            this.freight1 = new HashSet<freight>();
            this.hotel = new HashSet<hotel>();
            this.insure = new HashSet<insure>();
            this.order = new HashSet<order>();
            this.order1 = new HashSet<order>();
            this.order2 = new HashSet<order>();
            this.partner1 = new HashSet<partner>();
            this.reserve = new HashSet<reserve>();
            this.reserve1 = new HashSet<reserve>();
            this.reserve2 = new HashSet<reserve>();
            this.partner11 = new HashSet<partner>();
            this.service = new HashSet<service>();
            this.visapr = new HashSet<visapr>();
            this.payment = new HashSet<payment>();
            this.payment1 = new HashSet<payment>();
        }
    
        public int inc { get; set; }
        public int parttype { get; set; }
        public string name { get; set; }
        public string lname { get; set; }
        public int town { get; set; }
        public string address { get; set; }
        public string rs { get; set; }
        public string rsv { get; set; }
        public string inn { get; set; }
        public string okonh { get; set; }
        public string okpo { get; set; }
        public string owner { get; set; }
        public string boss { get; set; }
        public string workers { get; set; }
        public string passport { get; set; }
        public string phprefix { get; set; }
        public string phones { get; set; }
        public string phones1 { get; set; }
        public string phones2 { get; set; }
        public string faxes { get; set; }
        public string faxes1 { get; set; }
        public string email { get; set; }
        public string email1 { get; set; }
        public string www { get; set; }
        public Nullable<decimal> rate { get; set; }
        public string comment { get; set; }
        public string direction { get; set; }
        public Nullable<int> ident { get; set; }
        public bool internet { get; set; }
        public Nullable<bool> faxmailing { get; set; }
        public Nullable<bool> emailing { get; set; }
        public string officialname { get; set; }
        public string alias { get; set; }
        public System.Guid guid { get; set; }
        public string licence { get; set; }
        public string metro { get; set; }
        public string kpp { get; set; }
        public string bonuscard { get; set; }
        public Nullable<System.DateTime> adate { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public Nullable<short> author { get; set; }
        public Nullable<short> user { get; set; }
        public string addresscode { get; set; }
        public int rowner { get; set; }
        public string skey { get; set; }
        public string paddress { get; set; }
        public Nullable<int> headpartner { get; set; }
        public string accountname { get; set; }
        public string accountemail { get; set; }
        public string accountphones { get; set; }
        public byte[] stamp { get; set; }
        public string icq { get; set; }
        public string icq1 { get; set; }
        public Nullable<int> reason4blacklist { get; set; }
        public string bik1 { get; set; }
        public string bank { get; set; }
        public Nullable<bool> smsmailing { get; set; }
        public Nullable<bool> dontshowall { get; set; }
        public Nullable<int> metrostation { get; set; }
        public bool access2online4people { get; set; }
        public Nullable<int> ownership { get; set; }
        public Nullable<int> activity { get; set; }
        public Nullable<int> mainbank { get; set; }
        public bool recalc_commiss { get; set; }
        public string ogrn { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<System.DateTime> stopdate { get; set; }
        public Nullable<int> taxation { get; set; }
        public Nullable<System.DateTime> verification_date { get; set; }
        public Nullable<bool> black { get; set; }
        public string proxy_number { get; set; }
        public Nullable<System.DateTime> proxy_date { get; set; }
        public Nullable<int> director_position { get; set; }
        public string registry_number { get; set; }
        public bool enablepayclaim_bytourist { get; set; }
        public Nullable<int> partnercategory { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public string registration_serie { get; set; }
        public string registration_number { get; set; }
        public string registration_organ { get; set; }
        public bool agreement { get; set; }
        public Nullable<bool> notavail_wheretobuy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<claim> claim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<claim> claim1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<claim> claim2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<claim> claim3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<freight> freight { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<freight> freight1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hotel> hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insure> insure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> order1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> order2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partner> partner1 { get; set; }
        public virtual partner partner2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reserve> reserve { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reserve> reserve1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reserve> reserve2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partner> partner11 { get; set; }
        public virtual partner partner3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<service> service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visapr> visapr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment> payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment> payment1 { get; set; }
    }
}
