//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodwinService3
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public payment()
        {
            this.pdetail = new HashSet<pdetail>();
        }
    
        public int inc { get; set; }
        public Nullable<int> partner { get; set; }
        public Nullable<System.DateTime> pdate { get; set; }
        public Nullable<decimal> psum { get; set; }
        public Nullable<int> currency { get; set; }
        public bool cash { get; set; }
        public string note { get; set; }
        public string ndoc { get; set; }
        public string invoice { get; set; }
        public bool paid { get; set; }
        public bool fullassign { get; set; }
        public string rawinvoice { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<short> user { get; set; }
        public Nullable<decimal> saletax { get; set; }
        public Nullable<decimal> saletaxsum { get; set; }
        public Nullable<decimal> pay { get; set; }
        public Nullable<decimal> @return { get; set; }
        public Nullable<decimal> rest { get; set; }
        public int mtype { get; set; }
        public Nullable<System.DateTime> ridate { get; set; }
        public Nullable<int> payee { get; set; }
        public string insidenote { get; set; }
        public System.Guid guid { get; set; }
        public short author { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public string reservations { get; set; }
        public Nullable<int> oinc { get; set; }
        public Nullable<int> ktype { get; set; }
        public Nullable<int> phys_buyer { get; set; }
        public Nullable<int> partner_bank { get; set; }
        public Nullable<decimal> bank_commission { get; set; }
    
        public virtual currency currency1 { get; set; }
        public virtual partner partner1 { get; set; }
        public virtual partner partner2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pdetail> pdetail { get; set; }
    }
}
