//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodwinService3
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserve
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reserve()
        {
            this.order = new HashSet<order>();
            this.claim = new HashSet<claim>();
        }
    
        public int inc { get; set; }
        public string block { get; set; }
        public Nullable<System.DateTime> rtime { get; set; }
        public int resource { get; set; }
        public Nullable<System.DateTime> datebeg { get; set; }
        public Nullable<System.DateTime> dateend { get; set; }
        public Nullable<short> rcount { get; set; }
        public Nullable<int> partner { get; set; }
        public string resown { get; set; }
        public bool soft { get; set; }
        public Nullable<int> paydays { get; set; }
        public Nullable<int> canceldays { get; set; }
        public string time_in { get; set; }
        public string time_out { get; set; }
        public Nullable<int> owner { get; set; }
        public Nullable<int> releasedays { get; set; }
        public Nullable<int> tour { get; set; }
        public string note { get; set; }
        public Nullable<int> partner_parent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<claim> claim { get; set; }
        public virtual partner partner1 { get; set; }
        public virtual partner partner2 { get; set; }
        public virtual partner partner3 { get; set; }
    }
}
