//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodwinService3
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public service()
        {
            this.freight = new HashSet<freight>();
            this.freight1 = new HashSet<freight>();
            this.freight2 = new HashSet<freight>();
            this.freight3 = new HashSet<freight>();
            this.order = new HashSet<order>();
        }
    
        public int inc { get; set; }
        public string name { get; set; }
        public string lname { get; set; }
        public Nullable<int> servtype { get; set; }
        public Nullable<int> partner { get; set; }
        public Nullable<int> town { get; set; }
        public bool @private { get; set; }
        public Nullable<int> trantype { get; set; }
        public Nullable<short> minpax { get; set; }
        public Nullable<short> maxpax { get; set; }
        public bool commission { get; set; }
        public bool ienable2send { get; set; }
        public byte[] stamp { get; set; }
        public bool individual { get; set; }
        public Nullable<bool> conditional { get; set; }
        public string www { get; set; }
        public bool require { get; set; }
        public bool access { get; set; }
        public bool remove { get; set; }
        public Nullable<int> transfertype { get; set; }
        public int needhotel { get; set; }
        public int needtown { get; set; }
        public int needtarget { get; set; }
        public Nullable<int> color { get; set; }
        public int needairline { get; set; }
        public bool providedbyhotel { get; set; }
        public string note { get; set; }
        public string privatenote { get; set; }
        public bool packet { get; set; }
        public bool select_tourist { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<freight> freight { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<freight> freight1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<freight> freight2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<freight> freight3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> order { get; set; }
        public virtual partner partner1 { get; set; }
    }
}
