//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodwinService3
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.users1 = new HashSet<users>();
        }
    
        public short code { get; set; }
        public string name { get; set; }
        public string alias { get; set; }
        public byte[] pass { get; set; }
        public byte[] crc { get; set; }
        public Nullable<bool> enabled { get; set; }
        public Nullable<int> color { get; set; }
        public bool change_pass { get; set; }
        public Nullable<short> groupcode { get; set; }
        public string lname { get; set; }
        public string www { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<users> users1 { get; set; }
        public virtual users users2 { get; set; }
    }
}
