//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodwinService3
{
    using System;
    using System.Collections.Generic;
    
    public partial class visapr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public visapr()
        {
            this.order = new HashSet<order>();
        }
    
        public int inc { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> partner { get; set; }
        public Nullable<int> visa { get; set; }
        public Nullable<short> days { get; set; }
        public Nullable<bool> commission { get; set; }
        public byte[] stamp { get; set; }
        public Nullable<int> color { get; set; }
        public Nullable<short> givenwarndays { get; set; }
        public Nullable<short> warndays { get; set; }
        public int printtype { get; set; }
        public bool biometric { get; set; }
        public int calcagefrom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> order { get; set; }
        public virtual visa visa1 { get; set; }
        public virtual partner partner1 { get; set; }
    }
}
